name: Artifact

on: [push]

env:
    ARTIFACT_NAME: myartifact
jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - name: check out the code
              uses: actions/checkout@v2
            
            - name: upload the artifact
              uses: actions/upload-artifact@
              with:
                name: ${{anv.ARTIFACT_NAME}}
                path: .

